### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by guoweibo** [SleepyOcean/so-jpql-template-engine#3]
java.lang.NullPointerException
	at com.sleepy.jpql.JpqlParser.parse(JpqlParser.java:44)
按照教程 https://blog.csdn.net/stoneBridge1920/article/details/104053925 来的

**Comment by SleepyOcean** [comment]
4月份我做些了结构优化，csdn我很久没更新了，你可以参考本项目的readme的教程来。
